import { PrismaClient, AchievementCategory } from "@prisma/client";

const prisma = new PrismaClient();

// ─── Achievement definitions ──────────────────────────────────────────────────
// key:         unique code used in achievement-checking logic
// threshold:   numeric target for tiered achievements (null = one-off)
// isSecret:    hidden until earned (used for surprise/easter egg achievements)
// points:      displayed on profile, used for leaderboard sorting

const ACHIEVEMENTS = [
  // ── Library ────────────────────────────────────────────────────────────────
  {
    key: "LIBRARY_FIRST",
    name: "First Edition",
    description: "Add your first game to your library.",
    category: "LIBRARY",
    icon: "📖",
    points: 5,
    threshold: 1,
    sortOrder: 1,
  },
  {
    key: "LIBRARY_10",
    name: "Bookshelf",
    description: "Own 10 games.",
    category: "LIBRARY",
    icon: "📚",
    points: 10,
    threshold: 10,
    sortOrder: 2,
  },
  {
    key: "LIBRARY_25",
    name: "Collector",
    description: "Own 25 games.",
    category: "LIBRARY",
    icon: "🗃️",
    points: 20,
    threshold: 25,
    sortOrder: 3,
  },
  {
    key: "LIBRARY_50",
    name: "Curator",
    description: "Own 50 games.",
    category: "LIBRARY",
    icon: "🏛️",
    points: 40,
    threshold: 50,
    sortOrder: 4,
  },
  {
    key: "LIBRARY_100",
    name: "The Archivist",
    description: "Own 100 games. You have a problem. A wonderful problem.",
    category: "LIBRARY",
    icon: "🏰",
    points: 100,
    threshold: 100,
    sortOrder: 5,
  },
  {
    key: "WISHLIST_10",
    name: "Wishful Thinking",
    description: "Add 10 games to your wishlist.",
    category: "LIBRARY",
    icon: "⭐",
    points: 10,
    threshold: 10,
    sortOrder: 6,
  },
  {
    key: "LIBRARY_YEAR_OLD",
    name: "Vintage",
    description: "Own a game published before 1990.",
    category: "LIBRARY",
    icon: "🕰️",
    points: 15,
    threshold: null,
    sortOrder: 7,
  },
  {
    key: "LIBRARY_NEW",
    name: "Early Adopter",
    description: "Own a game published within the last year.",
    category: "LIBRARY",
    icon: "🆕",
    points: 10,
    threshold: null,
    sortOrder: 8,
  },

  // ── Geography ──────────────────────────────────────────────────────────────
  {
    key: "GEO_COUNTRIES_3",
    name: "Passport Stamp",
    description: "Own games from 3 different countries.",
    category: "GEOGRAPHY",
    icon: "🗺️",
    points: 15,
    threshold: 3,
    sortOrder: 1,
  },
  {
    key: "GEO_COUNTRIES_5",
    name: "World Traveler",
    description: "Own games from 5 different countries.",
    category: "GEOGRAPHY",
    icon: "🌍",
    points: 25,
    threshold: 5,
    sortOrder: 2,
  },
  {
    key: "GEO_COUNTRIES_10",
    name: "Globetrotter",
    description: "Own games from 10 different countries.",
    category: "GEOGRAPHY",
    icon: "🌐",
    points: 50,
    threshold: 10,
    sortOrder: 3,
  },
  {
    key: "GEO_CONTINENTS_3",
    name: "The Diplomat",
    description: "Own games from 3 different continents.",
    category: "GEOGRAPHY",
    icon: "✈️",
    points: 30,
    threshold: 3,
    sortOrder: 4,
  },
  {
    key: "GEO_EUROPE",
    name: "Eurogamer",
    description: "Own 5 games of European origin.",
    category: "GEOGRAPHY",
    icon: "🏰",
    points: 20,
    threshold: 5,
    sortOrder: 5,
  },
  {
    key: "GEO_JAPAN",
    name: "Rising Sun",
    description: "Own a game of Japanese origin.",
    category: "GEOGRAPHY",
    icon: "⛩️",
    points: 15,
    threshold: null,
    sortOrder: 6,
  },
  {
    key: "GEO_PLAY_COUNTRIES",
    name: "Around the World",
    description: "Log plays of games from 5 different countries.",
    category: "GEOGRAPHY",
    icon: "🧭",
    points: 35,
    threshold: 5,
    sortOrder: 7,
  },

  // ── Category ───────────────────────────────────────────────────────────────
  {
    key: "CAT_DIVERSE_5",
    name: "Renaissance Gamer",
    description: "Own games in 5 different BGG categories.",
    category: "CATEGORY",
    icon: "🎭",
    points: 20,
    threshold: 5,
    sortOrder: 1,
  },
  {
    key: "CAT_DIVERSE_10",
    name: "Polymath",
    description: "Own games in 10 different BGG categories.",
    category: "CATEGORY",
    icon: "🧠",
    points: 40,
    threshold: 10,
    sortOrder: 2,
  },
  {
    key: "CAT_WAR",
    name: "War Room",
    description: "Own 3 war games.",
    category: "CATEGORY",
    icon: "⚔️",
    points: 15,
    threshold: 3,
    sortOrder: 3,
  },
  {
    key: "CAT_MYSTERY",
    name: "Mystery Buff",
    description: "Own 3 mystery/deduction games.",
    category: "CATEGORY",
    icon: "🔍",
    points: 15,
    threshold: 3,
    sortOrder: 4,
  },
  {
    key: "CAT_FANTASY",
    name: "Fantasy Realm",
    description: "Own 5 fantasy games.",
    category: "CATEGORY",
    icon: "🧙",
    points: 20,
    threshold: 5,
    sortOrder: 5,
  },
  {
    key: "CAT_HISTORY",
    name: "History Lesson",
    description: "Own 3 historical games.",
    category: "CATEGORY",
    icon: "📜",
    points: 15,
    threshold: 3,
    sortOrder: 6,
  },
  {
    key: "CAT_PARTY",
    name: "Party Animal",
    description: "Own 5 party games.",
    category: "CATEGORY",
    icon: "🎉",
    points: 15,
    threshold: 5,
    sortOrder: 7,
  },
  {
    key: "CAT_COOP",
    name: "Team Player",
    description: "Own 5 cooperative games.",
    category: "CATEGORY",
    icon: "🤝",
    points: 20,
    threshold: 5,
    sortOrder: 8,
  },
  {
    key: "CAT_HORROR",
    name: "Things That Go Bump",
    description: "Own 3 horror games.",
    category: "CATEGORY",
    icon: "👻",
    points: 15,
    threshold: 3,
    sortOrder: 9,
  },

  // ── Mechanics ──────────────────────────────────────────────────────────────
  {
    key: "MECH_DECK_BUILD",
    name: "Deck Builder",
    description: "Own 3 deck-building games.",
    category: "MECHANIC",
    icon: "🃏",
    points: 15,
    threshold: 3,
    sortOrder: 1,
  },
  {
    key: "MECH_WORKER",
    name: "Worker Placement",
    description: "Own 3 worker placement games.",
    category: "MECHANIC",
    icon: "🧑‍🏭",
    points: 15,
    threshold: 3,
    sortOrder: 2,
  },
  {
    key: "MECH_DICE",
    name: "Roll With It",
    description: "Own 5 dice games.",
    category: "MECHANIC",
    icon: "🎲",
    points: 15,
    threshold: 5,
    sortOrder: 3,
  },
  {
    key: "MECH_AREA",
    name: "Area Control Freak",
    description: "Own 3 area control games.",
    category: "MECHANIC",
    icon: "🗾",
    points: 15,
    threshold: 3,
    sortOrder: 4,
  },
  {
    key: "MECH_DRAFT",
    name: "Drafting Table",
    description: "Own 3 card drafting games.",
    category: "MECHANIC",
    icon: "📋",
    points: 15,
    threshold: 3,
    sortOrder: 5,
  },
  {
    key: "MECH_LEGACY",
    name: "No Going Back",
    description: "Own a legacy or campaign game.",
    category: "MECHANIC",
    icon: "📝",
    points: 20,
    threshold: null,
    sortOrder: 6,
  },
  {
    key: "MECH_ASYMMETRIC",
    name: "Not Playing Fair",
    description: "Own 3 asymmetric games.",
    category: "MECHANIC",
    icon: "⚖️",
    points: 15,
    threshold: 3,
    sortOrder: 7,
  },
  {
    key: "MECH_TRAITOR",
    name: "Trust No One",
    description: "Own 2 hidden traitor games.",
    category: "MECHANIC",
    icon: "🎭",
    points: 15,
    threshold: 2,
    sortOrder: 8,
  },

  // ── Complexity ─────────────────────────────────────────────────────────────
  {
    key: "WEIGHT_LIGHT",
    name: "Casual Friday",
    description: "Own 5 games with a BGG weight under 2.0.",
    category: "COMPLEXITY",
    icon: "🌱",
    points: 10,
    threshold: 5,
    sortOrder: 1,
  },
  {
    key: "WEIGHT_MEDIUM",
    name: "Getting Serious",
    description: "Own 5 games with a BGG weight over 3.0.",
    category: "COMPLEXITY",
    icon: "🧩",
    points: 20,
    threshold: 5,
    sortOrder: 2,
  },
  {
    key: "WEIGHT_HEAVY",
    name: "Heavy Hitter",
    description: "Own a game with a BGG weight over 4.0.",
    category: "COMPLEXITY",
    icon: "🏋️",
    points: 30,
    threshold: null,
    sortOrder: 3,
  },
  {
    key: "WEIGHT_SPECTRUM",
    name: "The Full Spectrum",
    description: "Own at least one game in every weight tier (1–2, 2–3, 3–4, 4–5).",
    category: "COMPLEXITY",
    icon: "🌈",
    points: 40,
    threshold: null,
    sortOrder: 4,
  },

  // ── Ratings ────────────────────────────────────────────────────────────────
  {
    key: "RATE_FIRST",
    name: "Critic",
    description: "Rate your first game.",
    category: "RATINGS",
    icon: "⭐",
    points: 5,
    threshold: 1,
    sortOrder: 1,
  },
  {
    key: "RATE_10",
    name: "The Reviewer",
    description: "Rate 10 games.",
    category: "RATINGS",
    icon: "📝",
    points: 15,
    threshold: 10,
    sortOrder: 2,
  },
  {
    key: "RATE_25",
    name: "Opinionated",
    description: "Rate 25 games.",
    category: "RATINGS",
    icon: "🗣️",
    points: 25,
    threshold: 25,
    sortOrder: 3,
  },
  {
    key: "RATE_PERFECT",
    name: "Five Stars",
    description: "Give a 5-star rating.",
    category: "RATINGS",
    icon: "🌟",
    points: 10,
    threshold: null,
    sortOrder: 4,
  },
  {
    key: "RATE_HARSH",
    name: "The Critic",
    description: "Give a 1-star rating. Ouch.",
    category: "RATINGS",
    icon: "💀",
    points: 10,
    threshold: null,
    sortOrder: 5,
    isSecret: true,
  },

  // ── Social ─────────────────────────────────────────────────────────────────
  {
    key: "SOCIAL_JOIN_ROOM",
    name: "Pull Up a Chair",
    description: "Join your first room.",
    category: "SOCIAL",
    icon: "🪑",
    points: 5,
    threshold: null,
    sortOrder: 1,
  },
  {
    key: "SOCIAL_HOST_FIRST",
    name: "Host",
    description: "Host your first game night.",
    category: "SOCIAL",
    icon: "🏠",
    points: 10,
    threshold: 1,
    sortOrder: 2,
  },
  {
    key: "SOCIAL_HOST_5",
    name: "Regular",
    description: "Host 5 game nights.",
    category: "SOCIAL",
    icon: "🗓️",
    points: 20,
    threshold: 5,
    sortOrder: 3,
  },
  {
    key: "SOCIAL_HOST_25",
    name: "The Usual Spot",
    description: "Host 25 game nights.",
    category: "SOCIAL",
    icon: "🏆",
    points: 50,
    threshold: 25,
    sortOrder: 4,
  },
  {
    key: "SOCIAL_BIGGROUP",
    name: "The Ringleader",
    description: "Host a game night with 6 or more players.",
    category: "SOCIAL",
    icon: "👑",
    points: 20,
    threshold: 6,
    sortOrder: 5,
  },
  {
    key: "SOCIAL_PLAYERS_10",
    name: "Open Door",
    description: "Have 10 different players join your rooms.",
    category: "SOCIAL",
    icon: "🚪",
    points: 25,
    threshold: 10,
    sortOrder: 6,
  },
  {
    key: "SOCIAL_FOLLOW_10",
    name: "Community Member",
    description: "Follow 10 other players.",
    category: "SOCIAL",
    icon: "🤝",
    points: 15,
    threshold: 10,
    sortOrder: 7,
  },
  {
    key: "SOCIAL_FOLLOWED_10",
    name: "Fan Favorite",
    description: "Be followed by 10 other players.",
    category: "SOCIAL",
    icon: "❤️",
    points: 25,
    threshold: 10,
    sortOrder: 8,
  },

  // ── Play history ───────────────────────────────────────────────────────────
  {
    key: "PLAY_FIRST",
    name: "First Roll",
    description: "Log your first play session.",
    category: "PLAY",
    icon: "🎯",
    points: 5,
    threshold: 1,
    sortOrder: 1,
  },
  {
    key: "PLAY_10",
    name: "Seasoned",
    description: "Log 10 play sessions.",
    category: "PLAY",
    icon: "🎖️",
    points: 20,
    threshold: 10,
    sortOrder: 2,
  },
  {
    key: "PLAY_50",
    name: "Veteran",
    description: "Log 50 play sessions.",
    category: "PLAY",
    icon: "🎗️",
    points: 50,
    threshold: 50,
    sortOrder: 3,
  },
  {
    key: "PLAY_VARIETY",
    name: "Variety Pack",
    description: "Play games in 5 different BGG categories in logged sessions.",
    category: "PLAY",
    icon: "🎨",
    points: 25,
    threshold: 5,
    sortOrder: 4,
  },
  {
    key: "PLAY_SPEED",
    name: "Speed Round",
    description: "Log 3 games under 20 minutes in a single session.",
    category: "PLAY",
    icon: "⚡",
    points: 20,
    threshold: null,
    sortOrder: 5,
  },
  {
    key: "PLAY_EPIC",
    name: "Epic Journey",
    description: "Log a game lasting over 3 hours.",
    category: "PLAY",
    icon: "🏰",
    points: 25,
    threshold: null,
    sortOrder: 6,
  },
  {
    key: "PLAY_LONGNIGHT",
    name: "Long Night",
    description: "Log 4 or more games in a single session.",
    category: "PLAY",
    icon: "🌙",
    points: 20,
    threshold: null,
    sortOrder: 7,
  },
  {
    key: "PLAY_WIN",
    name: "Winner Winner",
    description: "Log a win.",
    category: "PLAY",
    icon: "🥇",
    points: 10,
    threshold: null,
    sortOrder: 8,
  },
  {
    key: "PLAY_WIN_10",
    name: "On a Roll",
    description: "Log 10 wins.",
    category: "PLAY",
    icon: "🏅",
    points: 25,
    threshold: 10,
    sortOrder: 9,
  },

  // ── Streaks ────────────────────────────────────────────────────────────────
  {
    key: "STREAK_4",
    name: "Weekly Ritual",
    description: "Host game nights 4 weeks in a row.",
    category: "STREAK",
    icon: "🔥",
    points: 30,
    threshold: 4,
    sortOrder: 1,
  },
  {
    key: "STREAK_8",
    name: "Dedicated",
    description: "Host game nights 8 weeks in a row.",
    category: "STREAK",
    icon: "💪",
    points: 60,
    threshold: 8,
    sortOrder: 2,
  },
  {
    key: "STREAK_12",
    name: "Creature of Habit",
    description: "Host game nights 12 weeks in a row.",
    category: "STREAK",
    icon: "🌟",
    points: 100,
    threshold: 12,
    sortOrder: 3,
  },
  {
    key: "STREAK_52",
    name: "Year-Rounder",
    description: "Host game nights 52 weeks in a row. Legendary.",
    category: "STREAK",
    icon: "👑",
    points: 500,
    threshold: 52,
    sortOrder: 4,
    isSecret: true,
  },
] as const;

async function main() {
  console.log("Seeding achievements...");

  for (const achievement of ACHIEVEMENTS) {
    await prisma.achievements.upsert({
      where: { key: achievement.key },
      update: {
        name: achievement.name,
        description: achievement.description,
        category: achievement.category as AchievementCategory,
        icon: achievement.icon,
        points: achievement.points,
        threshold: achievement.threshold ?? null,
        isSecret: (achievement as any).isSecret ?? false,
        sortOrder: achievement.sortOrder,
      },
      create: {
        key: achievement.key,
        name: achievement.name,
        description: achievement.description,
        category: achievement.category as AchievementCategory,
        icon: achievement.icon,
        points: achievement.points,
        threshold: achievement.threshold ?? null,
        isSecret: (achievement as any).isSecret ?? false,
        sortOrder: achievement.sortOrder,
      },
    });
  }

  console.log(`Seeded ${ACHIEVEMENTS.length} achievements.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
