export const GAMELIST_MDM = [
  "7 Wonders", 
  "Arcana", 
  "Ascension", 
  "Battlestar Galactica", 
  "Borogrove", 
  "Cards Against Humanity", 
  "Carnival", 
  "Catan", 
  "Chili Mafia", 
  "Citadels", 
  "Creature Clash!", 
  "CULTivate", 
  "Dialect",
  "Eminent Domain", 
  "Gloomhaven", 
  "Inhuman Conditions", 
  "Iwari", 
  "Kabuto Sumo", 
  "Munchkin Cthulu", 
  "Munchkin Critical Role",
  "Ninjato",
  "Pandemic", 
  "Parks", 
  "Radlands", 
  "Root", 
  "Scythe", 
  "Seasons",
  "Spirits of the Forest",
  "Steven Universe: Beach-A-Palooza Card Battling Game", 
  "Tang Garden", 
  "Tapeworm", 
  "Tichu", 
  "Tidal Blades: Heroes of the Reef", 
  "Trails", 
  "The Binding of Isaac: Four Souls", 
  "The Twelve Doctors", 
  "Veiled Fate", 
  "Volfyirion", 
  "Wingspan", 
  "Your Friend is Sad", 
  "Zombie Dice"
];

export const GAMELIST_TAD = [
  "7 Wonders",
  "Amazed",
  "Arkham Horror",
  "Ascension",
  "Avalon",
  "Betrayal at the House on the Hill",
  "Betrayal Legacy",
  "Bob Ross: Happy Little Accidents",
  "Castle Panic",
  "Catan",
  "Citadels",
  "Coup",
  "Dead of Winter",
  "Dead Panic",
  "Delve",
  "Dialect",
  "Dominion",
  "Elder Sign",
  "Eldritch Horror",
  "Expedition",
  "Firefly",
  "Fury of Dracula",
  "Jenga",
  "Loot of Lima",
  "Machina Arcana",
  "Mansions of Madness",
  "Melee",
  "Million Dollar Script",
  "Mysterium",
  "Pandemic",
  "Pit",
  "QE",
  "Quarriors",
  "Quest",
  "Race for the Galaxy",
  "Rolf",
  "Roll for the Galaxy",
  "Smash Up",
  "Takenoko",
  "The Binding of Isaac: Four Souls", 
  "The Faceless",
  "The Movie Movie Game",
  "The Resistance",
  "Ticket to Ride",
  "Two Rooms and a Boom",
  "What Do You Meme?"
]

export const GAMELIST_GROUP = [
  "7 Wonders", 
  "Amazed",
  "Arcana",
  "Arkham Horror",
  "Ascension", 
  "Avalon",
  "Battlestar Galactica", 
  "Betrayal at the House on the Hill",
  "Betrayal Legacy",
  "Bob Ross: Happy Little Accidents",
  "Borogrove",
  "Cards Against Humanity", 
  "Carnival", 
  "Castle Panic",
  "Catan", 
  "Chili Mafia", 
  "Citadels", 
  "Coup",
  "Creature Clash!", 
  "CULTivate", 
  "Dialect",
  "Dead of Winter",
  "Dead Panic",
  "Delve",
  "Dialect",
  "Dominion",
  "Elder Sign",
  "Eldritch Horror",
  "Eminent Domain",
  "Expedition",
  "Firefly",
  "Fury of Dracula",
  "Gloomhaven", 
  "Inhuman Conditions", 
  "Iwari",
  "Jenga",
  "Kabuto Sumo", 
  "Loot of Lima",
  "Manchina Arcana",
  "Mansions of Madness",
  "Melee",
  "Million Dollar Script",
  "Munchkin Cthulu", 
  "Munchkin Critical Role",
  "Mysterium",
  "Ninjato",
  "Pandemic", 
  "Parks",
  "Pit",
  "QE",
  "Quarriors",
  "Quest",
  "Race for the Galaxy",
  "Radlands",
  "Rolf",
  "Roll for the Galaxy",
  "Root", 
  "Scythe", 
  "Seasons",
  "Smash Up",
  "Spirits of the Forest",
  "Steven Universe: Beach-A-Palooza Card Battling Game", 
  "Takenoko",
  "Tang Garden", 
  "Tapeworm", 
  "Tichu", 
  "Tidal Blades: Heroes of the Reef", 
  "Trails", 
  "The Binding of Isaac: Four Souls", 
  "The Faceless",
  "The Movie Movie Game",
  "The Resistance",
  "The Twelve Doctors", 
  "Ticket to Ride",
  "Two Rooms and a Boom",
  "Veiled Fate", 
  "Volfyirion", 
  "What Do You Meme?",
  "Wingspan", 
  "Your Friend is Sad", 
  "Zombie Dice"
]

