export const GAMELIST = [
  "7 Wonders", 
  "Arcana", 
  "Ascension", 
  "Battlestar Galactica", 
  "The Binding of Isaac: Four Souls", 
  "Borogrove", 
  "Cards Against Humanity", 
  "Carnival", 
  "Catan", 
  "Chili Mafia", 
  "Citadels", 
  "Creature Clash!", 
  "CULTivate", 
  "Dialect",
  "Eminent Domain", 
  "Gloomhaven", 
  "Inhuman Conditions", 
  "Iwari", 
  "Kabuto Sumo", 
  "Munchkin Cthulu", 
  "Munchkin Critical Role",
  "Ninjato",
  "Pandemic", 
  "Parks", 
  "Radlands", 
  "Root", 
  "Scythe", 
  "Seasons",
  "Spirits of the Forest",
  "Steven Universe: Beach-A-Palooza Card Battling Game", 
  "Tang Garden", 
  "Tapeworm", 
  "Tichu", 
  "Tidal Blades: Heroes of the Reef", 
  "Trails", 
  "The Twelve Doctors", 
  "Veiled Fate", 
  "Volfyirion", 
  "Wingspan", 
  "Your Friend is Sad", 
  "Zombie Dice"];